"""update radiographies model

Revision ID: 448c6747ff86
Revises: 241fb5289831
Create Date: 2026-04-13 20:54:56.992126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448c6747ff86'
down_revision: Union[str, Sequence[str], None] = '241fb5289831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radiographies', sa.Column('full_name', sa.String(length=150), nullable=False))
    op.add_column('radiographies', sa.Column('patient_code', sa.String(length=50), nullable=False))
    op.add_column('radiographies', sa.Column('clinical_description', sa.String(length=255), nullable=False))
    op.add_column('radiographies', sa.Column('study_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_radiographies_patient_code'), 'radiographies', ['patient_code'], unique=True)
    op.drop_column('radiographies', 'diagnosis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radiographies', sa.Column('diagnosis', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_radiographies_patient_code'), table_name='radiographies')
    op.drop_column('radiographies', 'study_date')
    op.drop_column('radiographies', 'clinical_description')
    op.drop_column('radiographies', 'patient_code')
    op.drop_column('radiographies', 'full_name')
    # ### end Alembic commands ###
