"""remove unique from patient_code

Revision ID: 77e707154a24
Revises: 448c6747ff86
Create Date: 2026-04-13 22:05:43.159421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e707154a24'
down_revision: Union[str, Sequence[str], None] = '448c6747ff86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radiographies_patient_code'), table_name='radiographies')
    op.create_index(op.f('ix_radiographies_patient_code'), 'radiographies', ['patient_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radiographies_patient_code'), table_name='radiographies')
    op.create_index(op.f('ix_radiographies_patient_code'), 'radiographies', ['patient_code'], unique=1)
    # ### end Alembic commands ###
